<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>file_extensions</key>
    <array>
      <string>ram</string>
    </array>
    <key>name</key>
    <string>RamSim</string>
    <key>scope</key>
    <string>source.ram</string>
    <key>contexts</key>
    <dict>
      <key>main</key>
      <array>
        <dict>
          <key>match</key>
          <string>(?i)\b(include|halt|jump|jmp|jz|jzero|jgz|jgtz)\b</string>
          <key>scope</key>
          <string>keyword.control.c</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)\b(add|sub|mul|div|load|store|write|read)\b</string>
          <key>scope</key>
          <string>entity.name.function</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(?i)[a-z]+[:]</string>
          <key>scope</key>
          <string>variable.parameter.c++</string>
        </dict>
        <dict>
          <key>match</key>
          <string>"</string>
          <key>push</key>
          <string>string</string>
        </dict>
        <dict>
          <key>match</key>
          <string>\b[0-9]+\b</string>
          <key>scope</key>
          <string>constant.numeric.python</string>
        </dict>
        <dict>
          <key>match</key>
          <string>#</string>
          <key>scope</key>
          <string>punctuation.definition.comment.python</string>
          <key>push</key>
          <string>line_comment</string>
        </dict>
      </array>
      <key>string</key>
      <array>
        <dict>
          <key>meta_scope</key>
          <string>string.quoted.double.python</string>
        </dict>
        <dict>
          <key>match</key>
          <string>"</string>
          <key>pop</key>
          <true/>
        </dict>
      </array>
      <key>line_comment</key>
      <array>
        <dict>
          <key>meta_scope</key>
          <string>comment.line.python</string>
        </dict>
        <dict>
          <key>match</key>
          <string>$</string>
          <key>pop</key>
          <true/>
        </dict>
      </array>
    </dict>
  </dict>
</plist>